name: Build and publish Anno mod

on:
  workflow_dispatch:
    inputs:  
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  push:
    tags:
      - 'v*'

env:
  MOD_NAME: 'mrr0b3rt-rantian-imperium-ornaments'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build mod
        run: |
          mkdir dist
          mkdir dist/$MOD_NAME
          cp "${{ github.workspace }}/src/*" "dis/$MOD_NAME"
          zip -r dist/mod.zip dist/$MOD_NAME
      
      - name: Create release
        run: |
          gh release create "${{ github.ref_name }}" \
            dist/mod.zip \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for ${{ github.ref_name }}"
      
      - name: Upload to mod.io
        run: |
          echo "Uploading to mod.io"