name: Build and publish Anno mod

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  MOD_NAME: 'mrr0b3rt-rantian-imperium-ornaments'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build mod
        run: |
          mkdir dist
          mkdir dist/${{ env.MOD_NAME }}
          cp -a "${{ github.workspace }}/src/." "dist/${{ env.MOD_NAME }}/"

          cd dist && zip -r "${{ env.MOD_NAME }}_${{ github.ref_name }}.zip" "${{ env.MOD_NAME }}/"
      
      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="1.0.0"
          awk "/^## \\[$VERSION\\]/ {flag=1;next} /^## \\[/ {flag=0} flag" CHANGELOG.md > tmp_changelog.txt
          cat tmp_changelog.txt

      - name: Create release
        if: 1 == 2
        run: |
          gh release create "${{ github.ref_name }}" \
            "dist/${{ env.MOD_NAME }}_${{ github.ref_name }}.zip" \
            --title "${{ github.ref_name }}" \
            --latest \
            --notes "No Notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to mod.io
        if: 1 == 2
        run: |
          curl -X POST "https://g-${{ secrets.MODIO_GAME_ID }}.modapi.io/v1/games/${{ secrets.MODIO_GAME_ID }}/mods/${{ secrets.MODIO_MOD_ID }}/files" \
            -H "Authorization: Bearer ${{ secrets.MODIO_API_KEY }}" \
            -F "filedata=@dist/${{ env.MOD_NAME }}_${{ github.ref_name }}.zip" \
            -F "version=${{ github.ref_name }}" \
            -F "active=true"